### ISSUE TITLE
Raw info returned from Trello has a null value for email

### ISSUE THREAD

**Issue by joshrowley** [joshrowley/omniauth-trello#1]
The Trello API returns null for the email address, emailed Trello, here's their response, now need to implement:

> Hi Joshua,
> 
> Thanks for writing to us!
> 
> Try using scope 'read,write,account'. Account is an undocumented scope that should let you see the email address.
> 
> All the best,
> 
> Ben

**Comment by hakunin** [comment]
I it just me, or trello only returns your email address and not your coworkers? (I am not using business class btw)

**Comment by markodobric** [comment]
For me also, trello only returns my email address and for other users email is still NULL (free account).

**Comment by nschmidtg** [comment]
Same here! No emails from my coworkers returned...

**Comment by hb3b** [comment]
Same here @markodobric.
