### ISSUE TITLE
Expiration not being sent to endpoint

### ISSUE THREAD

**Issue by tommybstitch** [joshrowley/omniauth-trello#5]
I am setting :expiration => 'never' in my omniauth.rb file, but I am only getting keys for 30 days every single time. What am I doing wrong here? My scope and my app_name are working, but not my expiration.

**Comment by joshrowley** [comment]
According to [the examples in Trello's docs](https://trello.com/docs/gettingstarted/index.html#getting-a-token-from-a-user), `expiration: 'never'` should be correct. Does passing in `1day` as the `expiration` param change the token's expiration date?

**Comment by tommybstitch** [comment]
It doesn't. It doesn't seem like my expiration parameter is getting passed at all.

**Comment by joshrowley** [comment]
Okay, I'll investigate once I have some free time this week.

**Comment by gregorym** [comment]
:+1:

**Comment by joshrowley** [comment]
Hey, is this still an issue for people? If so, I'd welcome any pull requests to make it happen 😁

**Comment by joshrowley** [comment]
Closing, if this is still an issue, will gladly accept pull requests.
